language: php 

compiler:
  - gcc

os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS="-q"

sudo: true

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install cmake doxygen -y
  - sudo ./travis/install_opencc.sh

before_script:
    - phpize
    - ./configure --quiet
    - sudo make

script:
    - make test 
